# Frontend
FROM node:14-slim
# update apt
RUN apt update && apt upgrade -y --no-install-recommends
# install vue-cli
RUN npm install -g @vue/cli
# install yarn
RUN apt install -y python procps yarn build-essential git

